# 因为之前的数据自增列不统一。

# 所以如果单独添加的话。1.需要先创建表，2.然后添加数据，3.然后添加主键自增列。

CREATE TABLE `cn_region_info` (
  `CRI_CODE` varchar(40) NOT NULL COMMENT '代码',
  `CRI_NAME` varchar(50) NOT NULL COMMENT '名称',
  `CRI_SHORT_NAME` varchar(20) NOT NULL COMMENT '简称',
  `CRI_SUPERIOR_CODE` varchar(40) DEFAULT NULL COMMENT '上级代码',
  `CRI_LNG` varchar(20) DEFAULT NULL COMMENT '经度',
  `CRI_LAT` varchar(20) DEFAULT NULL COMMENT '纬度',
  `CRI_SORT` int(6) DEFAULT NULL COMMENT '排序',
  `CRI_GMT_CREATE` datetime DEFAULT NULL COMMENT '创建时间',
  `CRI_GMT_MODIFIED` datetime DEFAULT NULL COMMENT '修改时间',
  `CRI_MEMO` varchar(250) DEFAULT NULL COMMENT '备注',
  `CRI_DATA_STATE` int(11) DEFAULT NULL COMMENT '状态',
  `CRI_TENANT_CODE` varchar(32) DEFAULT NULL COMMENT '租户ID',
  `CRI_LEVEL` varchar(11) DEFAULT NULL COMMENT '级别',
  KEY `Index_1` (`CRI_CODE`,`CRI_TENANT_CODE`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='中国地区信息';

ALTER TABLE cn_region_info ADD CRI_ID INT NOT NULL COMMENT '自增ID' PRIMARY KEY AUTO_INCREMENT FIRST;